# system configuration generated and used by the sysconfig module
build_time_vars = {'ABIFLAGS': '',
 'AR': 'ar',
 'ARFLAGS': 'rc',
 'CC': 'gcc -pthread -arch arm64',
 'CCSHARED': '-fPIC',
 'CFLAGS': '-DNDEBUG -O2',
 'CONFINCLUDEPY': '/Users/matti/build-worker-arm64/pypy-c-jit-macos-arm64/build/include/pypy3.10',
 'CXX': 'g++ -pthread -arch arm64',
 'EXE': '',
 'EXT_SUFFIX': '.pypy310-pp73-darwin.so',
 'GNULD': 'yes',
 'HOST_GNU_TYPE': 'arm-apple-darwin23.6.0',
 'INCLUDEPY': '/Users/matti/build-worker-arm64/pypy-c-jit-macos-arm64/build/include/pypy3.10',
 'LDCXXSHARED': 'c++ -shared -Wl,-O1 -Wl,-Bsymbolic-functions',
 'LDFLAGS': '-undefined dynamic_lookup',
 'LDLIBRARY': 'libpypy3.9-c.dylib',
 'LDSHARED': 'gcc -pthread -arch arm64 -shared -undefined dynamic_lookup',
 'LDVERSION': '3.10',
 'LIBDIR': '/Users/matti/build-worker-arm64/pypy-c-jit-macos-arm64/build/bin',
 'MACOSX_DEPLOYMENT_TARGET': '11.0',
 'MULTIARCH': 'darwin',
 'OPT': '-DNDEBUG -O2',
 'Py_DEBUG': 0,
 'Py_ENABLE_SHARED': 0,
 'SHLIB_SUFFIX': '.so',
 'SIZEOF_VOID_P': 8,
 'SO': '.pypy310-pp73-darwin.so',
 'SOABI': 'pypy310-pp73',
 'TZPATH': '/Users/matti/build-worker-arm64/pypy-c-jit-macos-arm64/build/share/zoneinfo:/Users/matti/build-worker-arm64/pypy-c-jit-macos-arm64/build/lib/zoneinfo:/Users/matti/build-worker-arm64/pypy-c-jit-macos-arm64/build/share/lib/zoneinfo:/Users/matti/build-worker-arm64/pypy-c-jit-macos-arm64/build/../etc/zoneinfo:/usr/share/zoneinfo:/usr/lib/zoneinfo:/usr/share/lib/zoneinfo:/etc/zoneinfo',
 'VERSION': '3.10',
 'WITH_DYLD': 1}
